#!/usr/bin/env python

#-----------------------------------------------------------------------
# keys.py
# Author: Bob Dondero
#-----------------------------------------------------------------------

# This file defines a key that should be kept secret. So don't place
# it in your GitHub repository -- just in case your GitHub repository
# accidentally becomes public.

# Generated by os.urandom(16)
APP_SECRET_KEY = b'\xcdt\x8dn\xe1\xbdW\x9d[}yJ\xfc\xa3~/'
